config/routes.rb
Rails.application.routes.draw do
  devise_for :companies
  root 'welcome#index'
  resources :activities, only: [:index]

  get '/about_us' => 'welcome#about_us'

  devise_scope :company do
  match 'companies/sign_out', to: 'devise/sessions#destroy', via: 'delete'
  end
  devise_scope :individual do
    match 'individuals/sign_out', to: 'devise/sessions#destroy', via: 'delete'
  end

  devise_for :individuals, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations"}
resources :profiles do
  get :autocomplete_tag_name, :on => :collection
end
  resources :individuals do
    resource :profile do
    member do
      post :follow_individual
      post :unfollow_individual
      post :portfolio_photo_uplaod
      post :resume_upload
      post :delete_portfolio
      post :delete_video
      post :update_profile
      end
    end
  end
  get 'tags/:tag' => 'events#index', as: :tag
  get 'classify/:with_classify' => 'events#index', as: :with_classify

  resources :companies do
    resource :company_profile do
      member do
        post :follow_company
        post :unfollow_company
      end
    end
    resources :events do
      member do
        post :follow_event
        post :unfollow_event

      end
      collection do
        get :new_job
      end
      get :job_pending
    end
    resources :company_profiles do
      collection do
        get :job_status
      end
    end

  end

  resources :events do
    collection do
      post 'request_create'
      get 'jobs'
    end
  end
resources :request_events
  resources :videos do
    collection do
      post :create
    end
  end

  resources :categories

resources :projects
  resources :queries do
    collection do
      post :create
    end
  end

resources :seekers

  resources :xviumer_profiles do
    collection do
    get :job_approval
    post :job_approve
      end
  end

  resources :job_feeds

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :individual
  belongs_to :category
  has_many :individual_photos
  has_many :videos
  has_one :document
  accepts_nested_attributes_for :individual_photos
  # enum individual_type: { professional: 0, jobseeker: 1, student: 2}
  acts_as_taggable_on :tags
  acts_as_followable
  has_attached_file :avatar, :styles => { :small => "150x150>" },
                    :s3_protocol => :https,
                    :url => ':s3_domain_url',
                    :path => '/avatars/:id/:style_:basename.:extension'


  # validates_attachment_presence :avatar, :message => 'Please select an image to upload'
  validates_attachment_size :avatar, :less_than => 2.megabytes, :message => 'Please select an image less than 2 MB'
   validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png', 'image/jpg'], :message => 'Please upload image only'

  filterrific :default_filter_params => { :sorted_by => 'created_at_desc' },
              :available_filters => %w[
                sorted_by
                search_query
                with_category_id

                with_type

              ]

  # default for will_paginate
  self.per_page = 9

  # scope :with_place, lambda { |place|
  #                    where( locality: place )
  #
  #                  }
  # scope :with_classify, lambda { |classify|
  #                       where( job_classify: classify )
  #
  #                     }
  scope :with_type, lambda { |type|
                    where(individual_type: type)
                  }

  scope :with_category_id, lambda { |category_ids|
                           where(category_id: [*category_ids])
                         }

  scope :search_query, lambda { |query|

                       where("first_name LIKE ?", "%#{query}%")
                     }

  scope :sorted_by, lambda { |sort_option|
                    # extract the sort direction from the param value.
                    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
                    case sort_option.to_s
                      when /^created_at_/
                        # Simple sort on the created_at column.
                        # Make sure to include the table name to avoid ambiguous column names.
                        # Joining on other tables is quite common in Filterrific, and almost
                        # every ActiveRecord table has a 'created_at' column.
                        order("profiles.created_at #{ direction }")
                      when /^name_/
                        # Simple sort on the name colums
                        order("LOWER(students.last_name) #{ direction }, LOWER(students.first_name) #{ direction }")
                      when /^country_name_/
                        # This sorts by a student's country name, so we need to include
                        # the country. We can't use JOIN since not all students might have
                        # a country.
                        order("LOWER(countries.name) #{ direction }").includes(:country)
                      else
                        raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
                    end
                  }

  def self.options_for_sorted_by
    [
        ['Name (a-z)', 'name_asc'],
        ['Registration date (newest first)', 'created_at_desc'],
        ['Registration date (oldest first)', 'created_at_asc'],
        ['Country (a-z)', 'country_name_asc']
    ]
  end

end
                                                                                 

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  protect_from_forgery except: :resume_upload
  before_action :authenticate_individual!, except: [:show, :follow_individual, :unfollow_individual]
  before_action :find_profile, only: [:show, :edit, :update, :destroy, :follow_individual, :unfollow_individual, :update_profile]
  # before_action :redirect_to_profile_create, :except => [:new, :create, :destroy, :autocomplete_tag_name]
  autocomplete :tag, :name, :class_name => 'ActsAsTaggableOn::Tag', :full => true

   # skip_before_action :redirect_to_profile_create, :only => [:new, :create, :destroy]
  # autocomplete :tag, :name, :class_name => 'ActsAsTaggableOn::Tag'

  def index
    @profiles = Profile.all
  end

  def new
    @profile = current_individual.build_profile
    @categories = Category.all
    p @categories
  end

  def create

    @categories = Category.all
    p params

    number_to_send_to = params[:profile][:contact_no]
    p number_to_send_to

    twilio_sid = "AC49d1afb324109edf5638a687ea7c2dcc"
    twilio_token = "a87772c81432ac1dfa07528ce1f003c4"
    twilio_phone_number = "719-428-4401"
    @profile = current_individual.build_profile(profile_params)
    if @profile.save
      # begin
      #   @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token
      #
      #   @twilio_client.account.sms.messages.create(
      #       :from => "+1#{twilio_phone_number}",
      #       :to => "+91#{number_to_send_to}",
      #       :body => "Welcome to the world of Lets Login, Your Profile has been successfully created."
      #   )
      # rescue Twilio::REST::RequestError => e
      #   puts e.message
      # end
      flash[:success] = "Profile saved"
      redirect_to  individual_profile_path(current_individual)
    else
      flash[:error] = find_error(@profile)
      render :new
    end
  end

  def update

    p params
    p 'hello'

    if @profile.update(avatar_params)
    @message = 'Avatar has successfully been uplaoded'
    respond_to do |format|
      format.html { redirect_to individual_profile_path(current_individual), notice: 'Avatar successfully updated.' }
      format.js { render :layout => false }
    end
    else
      respond_to do |format|
        format.html { redirect_to individual_profile_path(current_individual), alert: find_error(@profile) }
        format.js { render :layout => false }
      end
    @message = find_error(@profile)
      p @message
    end

    # redirect_to  individual_profile_path(current_individual)
  end

  def edit
   @categories = Category.all
  end

  def update_profile
    @categories = Category.all
    if @profile.update(profile_params)
      @message = 'Your profile has successfully been updated'
      respond_to do |format|
        format.html { redirect_to individual_profile_path(current_individual), notice: 'Your profile has successfully been updated' }
        format.js { render :layout => false }
      end
    else
      respond_to do |format|
        format.html { redirect_to edit_profile_path(@profile), alert: find_error(@profile) }
        format.js { render :layout => false }
      end
      @message = find_error(@profile)
      p @message
    end
  end

  def show
    p 'popopopoppop'
    p @profile.id
    p params
    p params[:id]
    p @profile.id
    @portfolio_photo = IndividualPhoto.new
    @profile_photos = IndividualPhoto.where(profile_id: @profile.id)
    p ' aaaaaaa'
    p @profile.individual_photos
    if company_signed_in?
    @find_req =  RequestEvent.where("individual_id = :individual_id and company_id = :company_id",
        { individual_id: params[:individual_id], company_id: current_company.id }).first
 if @find_req.present?
    @request_approve =  RequestEvent.where(id: @find_req.id).first
 end


    end
    @resume = Document.where(profile_id: @profile.id)
    @profile_videos = Video.where(profile_id: @profile.id)
  end

  def portfolio_photo_uplaod
    portfolio_photo_params[:portfolio_photos].each do |photo|
      IndividualPhoto.create(portfolio_photo: photo, profile_id: portfolio_photo_params[:profile_id])
    end
    redirect_to individual_profile_path(current_individual)
  end

  def follow_individual
    if individual_signed_in? && @profile.individual_id != current_individual.id
      current_individual.follow(@profile)
    elsif company_signed_in?
      current_company.follow(@profile)
    end
    p 'followed'
    respond_to do |format|
      format.js { render :layout => false }
    end
  end

  def unfollow_individual
    if individual_signed_in? && @profile.individual_id != current_individual.id
      current_individual.stop_following(@profile)
    elsif company_signed_in?
      current_company.stop_following(@profile)
    end
    p 'unfollowed'
    respond_to do |format|

      format.js { render 'follow_individual.js.erb'}
    end
  end

  def resume_upload

    p params
    @resume = Document.create(resume_params)
    if @resume.save
      respond_to do |format|
      format.html { redirect_to individual_profile_path(current_individual), notice: 'Resume successfully uploaded.' }
      format.js { render :layout => false }
      end
    else
      respond_to do |format|
      format.html { redirect_to individual_profile_path(current_individual), alert: find_error(@resume) }
      format.js { render :layout => false }
      end
    end

  end

  def delete_portfolio
    p params
    @photo =  IndividualPhoto.where(id: params[:portfolio]).first
    if @photo.destroy
    respond_to do |format|
      format.html { redirect_to individual_profile_path(current_individual), notice: 'Image successfully deleted.' }
      format.js { render :layout => false }
    end
    end

  end


  private

  def find_profile
      @profile = Profile.where(individual_id: params[:individual_id]).first
    p @profile

  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :birth_date,
                                    :gender, :bio, :personal_website, :linkedin_profile, :description, :contact_no, :facebook_profile, :category_id, :individual_type,
                                    :mobile_no, :telephone_no, :tag_list, :age, :twitter_profile, :avatar, :work_experience, :education,
                                    :month_salary, :hr_salary,:area_interest => [],:looking_job => [], :weekday_availability => [], :weekend_availability => [])
  end

  def avatar_params
    params.require(:profile).permit(:avatar)
  end
  def portfolio_photo_params
    params.permit(:profile_id, :portfolio_photos => [])
  end

  def resume_params
    params.permit(:profile_id, :document, :name)
  end

end

app/views/profiles/_resume_upload.html.erb
<div style="background: #ee6e73; width: 100%;"><h3 class="center-align" style="color: #fff;font-weight: 600 !important;">Upload CV</h3></div>
<div class="modal-content">
  <%= form_for(Document.new, :url => resume_upload_individual_profile_path, :html => {:multipart => true, :remote => true } ) do |f| %>
  <%#= form_tag  resume_upload_individual_profile_path, :multipart => true do  %>
      <%#= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <%= hidden_field_tag :profile_id, @profile.id %>
      <div class="row">

        <div class="file-field input-field">
          <div class="btn">
            <span>Choose Document</span>
            <i class="material-icons prefix">input</i>
            <%= file_field_tag :document, :required => true %>
          </div>
          <div class="file-path-wrapper">
            <input class="file-path validate" type="text">
          </div>
        </div>

      </div>

      </div>
      <div class="modal-footer">
        <button type="submit" style="float: left;margin-top: 0%;" class="waves-effect waves-light btn-large  "><i class="material-icons left">cloud</i>Submit</button>
        <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Close</a>
      </div>
  <% end %>

app/views/profiles/_upload_portfolio.html.erb
<%= stylesheet_link_tag 'dropify' %>
<%#= stylesheet_link_tag 'demo-dropify' %>
<div class="modal-content">



    <!--<a href="https://github.com/JeremyFagis/dropify" target="_blank"><img style="position: fixed; top: 0; right: 0; border: 0; z-index: 1000;" src="https://camo.githubusercontent.com/38ef81f8aca64bb9a64448d0d70f1308ef5341ab/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f6461726b626c75655f3132313632312e706e67" alt="Upload images" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png"></a>-->
  <% if individual_signed_in? && @profile.individual_id == current_individual.id %>
      <%= form_for @portfolio_photo, :url => portfolio_photo_uplaod_individual_profile_path(:profile_id => current_individual.profile.id), :method => :POST, :html => { :multipart => true } do |f| %>
          <%= f.hidden_field :profile_id, :value => current_individual.profile.id %>

      <div class="row">

        <div class="col s3" style="width: 32%">


                  <input type="file" name="portfolio_photos[]" id="input-file-to-destroy" class="dropify"  data-max-file-size="2M" data-max-height="2000" />
        </div>
        <div class="col s3" style="width: 32%">
          <input type="file" name="portfolio_photos[]" id="input-file-to-destroy" class="dropify"  data-max-file-size="2M" data-max-height="2000" />
        </div>
        <div class="col s3" style="width: 32%">


          <input type="file" name="portfolio_photos[]" id="input-file-to-destroy" class="dropify" data-max-file-size="2M" data-max-height="2000" />
        </div>




          <!--<label for="input-file-to-destroy">Multiple options are available</label>-->

</br>
          <!--<p class="help">Only portrait or square images, 2M max and 2000px max-height.</p>-->


      </div>





</div>
<div class="modal-footer row">
  <%= f.submit "Upload Images", :class =>'waves-green btn', :style => 'margin-top: 38px;font-weight: 500 !important;' %>
  <div class="right">


  </div>
      <% end %>
  <% end %>

  <script>

      // Basic
      $('.dropify').dropify();

      // Translated


      // Used events
      var drEvent = $('#input-file-events').dropify();

      drEvent.on('dropify.beforeClear', function(event, element){
          return confirm("Do you really want to delete \"" + element.file.name + "\" ?");
      });

      drEvent.on('dropify.afterClear', function(event, element){
          alert('File deleted');
      });

      drEvent.on('dropify.errors', function(event, element){
          console.log('Has Errors');
      });

      var drDestroy = $('#input-file-to-destroy').dropify();
      drDestroy = drDestroy.data('dropify')
      $('#toggleDropify').on('click', function(e){
          e.preventDefault();
          if (drDestroy.isDropified()) {
              drDestroy.destroy();
          } else {
              drDestroy.init();
          }
      })

  </script>
</div>

app/views/profiles/_upload_videos.html.erb
<div style="background: #ee6e73; width: 100%;"><h3 class="center-align" style="color: #fff;font-weight: 600 !important;">Upload Video</h3></div>
  <div class="modal-content">
    <%= form_for Video.new, :url => videos_path(@profile) do |f| %>
        <%= f.hidden_field :profile_id, :value => @profile.id %>
    <div class="row">
      <div class="input-field col s6">
        <i class="material-icons prefix">theaters</i>
        <%= f.text_field :link %>
        <label for="link">Youtube link</label>
      </div>
    </div>

  </div>
  <div class="modal-footer">
    <button type="submit" style="float: left;margin-top: 0%;" class="waves-effect waves-light btn-large  "><i class="material-icons left">cloud</i>Submit</button>
    <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Close</a>
  </div>
    <% end %>

app/views/profiles/follow_individual.js.erb
$('#follow-button-placeholder').load(document.URL +  ' #follow-button');
$('#follow-count-placeholder').load(document.URL +  ' #followed-count');

app/views/profiles/profile_backup.html.erb
<style>
    /* text-based popup styling */
    .white-popup {
        position: relative;
        background: #FFF;
        padding: 25px;
        width: auto;
        max-width: 400px;
        margin: 0 auto;
    }

    /*

    ====== Zoom effect ======

    */
    .mfp-zoom-in {
        /* start state */
        /* animate in */
        /* animate out */
    }
    .mfp-zoom-in .mfp-with-anim {
        opacity: 0;
        transition: all 0.2s ease-in-out;
        transform: scale(0.8);
    }
    .mfp-zoom-in.mfp-bg {
        opacity: 0;
        transition: all 0.3s ease-out;
    }
    .mfp-zoom-in.mfp-ready .mfp-with-anim {
        opacity: 1;
        transform: scale(1);
    }
    .mfp-zoom-in.mfp-ready.mfp-bg {
        opacity: 0.8;
    }
    .mfp-zoom-in.mfp-removing .mfp-with-anim {
        transform: scale(0.8);
        opacity: 0;
    }
    .mfp-zoom-in.mfp-removing.mfp-bg {
        opacity: 0;
    }
    .header-link {
        color: #fff !important;
    }
</style>

<%= render :partial => 'shared/header_profiles' %>
<div id="header" style="margin-top: 50px !important;">
  <div class="top">

    <!-- Logo -->

    <div id="logo">

      <% if @profile.avatar_file_name.nil? %>
          <a href="#test-popup" id="inline-popups" class="image avatar48" style="width: 100%; height: 120px;" data-effect="mfp-zoom-in"><img src="/assets/avatar.jpg"  alt="" /></a>
      <% else %>
          <a href="#test-popup" id="inline-popups" class="image avatar48" style="width: 100%; height: 120px;" data-effect="mfp-zoom-in"> <%= image_tag @profile.avatar.url %></a>
      <% end %>
      <div id="test-popup" class="white-popup mfp-with-anim mfp-hide">
        <%= form_for @profile, :url => { :action => "update"} do |avatar| %>
            <%= avatar.file_field :avatar %>
            <%= avatar.submit 'Update Picture' %>
        <% end %>
      </div>


      <h1 style="margin-left: -10px !important;" id="title"><%=@profile.first_name %> <%=@profile.last_name %> </h1>
      <p style="font-size: 20px"><%= @profile.individual_type %></p>


      <!--<a href="#0" class="cd-popup-trigger">View Pop-up</a>-->
      <!--<div class="cd-popup" role="alert">-->
      <!--<div class="cd-popup-container">-->
      <!--<p id="text-para" class="text-para">Are you sure you want to delete this element?</p>-->
      <!--<ul class="cd-buttons">-->

      <!--<li><button type="submit" value="accept"></button></li>-->


      <!--</ul>-->
      <!--<a href="#0" class="cd-popup-close img-replace">Close</a>-->
      <!--</div>-->
      <!--</div> -->

    </div>
    <a href="#" class="icon fa-users fa-1x "><span class="follower-count" id="followed-count"><%= @profile.followers_count %> followers</span></a></br>
    <div id="follow-button">
      <% if individual_signed_in? %>
          <% if current_individual.following?(@profile)  %>
              <%= form_tag (unfollow_individual_individual_profile_path), :remote => true, :id => 'unfollow-form' do  %>
                  <%= button_tag 'unfollow', :type => 'submit', :class => 'btn btn-default' %>
              <% end %>
          <% elsif @profile.individual_id == current_individual.id %>
          <% else %>
              <%= form_tag (follow_individual_individual_profile_path), :remote => true, :id => 'follow-form' do  %>
                  <%= button_tag 'follow', :type => 'submit', :class => 'btn btn-default' %>
              <% end %>
          <% end %>
      <% elsif company_signed_in? %>
          <% if current_company.following?(@profile) %>
              <%= form_tag (unfollow_individual_individual_profile_path), :remote => true, :id => 'unfollow-form' do  %>
                  <%= button_tag 'unfollow', :type => 'submit', :class => 'btn btn-default' %>
              <% end %>
          <% else %>
              <%= form_tag (follow_individual_individual_profile_path), :remote => true, :id => 'follow-form' do  %>
                  <%= button_tag 'follow', :type => 'submit', :class => 'btn btn-default' %>
              <% end %>
          <% end %>
      <% else %>
          please sign in to follow
      <% end %>
    </div>

    <!-- Nav -->
    <nav id="nav">
      <!--

          Prologue's nav expects links in one of two formats:

          1. Hash link (scrolls to a different section within the page)

             <li><a href="#foobar" id="foobar-link" class="icon fa-whatever-icon-you-want skel-layers-ignoreHref"><span class="label">Foobar</span></a></li>

          2. Standard link (sends the user to another page/site)

             <li><a href="http://foobar.tld" id="foobar-link" class="icon fa-whatever-icon-you-want"><span class="label">Foobar</span></a></li>

      -->
      <ul>
        <li><a href="#top" id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-home">Intro</span></a></li>
        <li><a href="#portfolio" id="portfolio-link" class="skel-layers-ignoreHref"><span class="icon fa-th">Portfolio</span></a></li>
        <li><a href="#about" id="about-link" class="skel-layers-ignoreHref"><span class="icon fa-user">About Me</span></a></li>
        <li><a href="#contact" id="contact-link" class="skel-layers-ignoreHref"><span class="icon fa-envelope">Contact</span></a></li>
      </ul>
    </nav>
    <% if company_signed_in? && @find_req.present? %>
        <% if  @find_req.status == "inprocess"  && @find_req.company_id.to_s == current_company.id.to_s %>
            <%= form_for @request_approve, :url => request_event_path(@request_approve.id), :method => :PATCH do |f| %>
                <%= f.hidden_field :status, :value => "onhold" %>
                <%= f.submit "Onhold" %>
            <% end %>

        <% elsif @find_req.status == "onhold"  && @find_req.company_id.to_s == current_company.id.to_s %>

            <%= form_for @request_approve, :url => request_event_path(@request_approve.id), :method => :PATCH do |f| %>
                <%= f.hidden_field :status, :value => "approved" %>
                <%= f.submit "Approve" %>
            <% end %>
            <%= form_for @request_approve, :url => request_event_path(@request_approve.id), :method => :PATCH do |f| %>
                <%= f.hidden_field :status, :value => "rejected" %>
                <%= f.submit "Reject" %>
            <% end %>

            <%#= form_tag ( edit_request_event_path(@find_req)), method: :patch do  %>
            <%#= hidden_field_tag :status, :value => "onhold" %>
            <%#= submit_tag "Approve" %>
            <%# end %>
        <% end %>
    <% end %>

  </div>


  <div class="bottom">


    <!-- Social Icons -->
    <ul class="icons">
      <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
      <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
      <li><a href="#" class="icon fa-github"><span class="label">Github</span></a></li>
      <li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
      <li><a href="#" class="icon fa-envelope"><span class="label">Email</span></a></li>
    </ul>

  </div>

</div>

<!-- Main -->
<div id="main">

  <!-- Intro -->
  <section id="top">
    <!--<img src="/assets/coverphoto.jpg" id="cover1" alt="" />-->

    <!--Details Table-->

    <h2><small>My Details</small></h2>
    <div class="well"><% @profile.tag_list.each do |tag| %>
                    <span class="tag label label-info"><%= link_to tag, tag_path(tag) %></span>
                <% end %>
      <table class="table table-striped">
        <tbody>
        <tr>
          <td>Category</td>
          <td><%= @profile.category.name unless @profile.category.blank? %></td>
        </tr>
        <tr>
          <td>Jobs preferred</td>
          <td> <%= JSON.parse(@profile.looking_job).join(', ')  %></td>
        </tr>
        <tr>
          <td>skills</td>
          <td> <% @profile.tag_list.each do |tag| %>
                <span class="tag label label-info"><%= link_to tag, tag_path(tag) %></span>
            <% end %>
          </td>
        </tr>
        <tr>
          <td>Salary Expected</td>
          <td>Monthly : <%= @profile.month_salary %></br>Weekly : <%= @profile.hr_salary %>
          </td>
        </tr>
        <tr>
          <td>availability</td>
          <td>Weekday : <%= JSON.parse(@profile.weekday_availability).join(', ')  %><br>Weekend :
            <%= JSON.parse(@profile.weekend_availability).join(', ')  %> </td>
        </tr>
        </tbody>
      </table>
    </div>



  </section>

  <!-- Portfolio -->
  <section id="portfolio" class="two">


    <div class="container">

      <header>
        <h2>Portfolio</h2>
      </header>
      <% if true %>
          No Data available
      <% else %>
          <div class="row">
            <% if individual_signed_in? && @profile.individual_id == current_individual.id %>
                <div class="col-md-4">
                  <a href="#" id="upload-event">Upload Photos</a>
                  <div id="upload-photo" style="display: none;">
                    <%= form_for @portfolio_photo, :url => portfolio_photo_uplaod_individual_profile_path(:profile_id => current_individual.profile.id), :method => :POST, :html => { :multipart => true } do |f| %>
                        <%= f.hidden_field :profile_id, :value => current_individual.profile.id %>
                        <%= file_field_tag 'portfolio_photos[]', multiple: true %>
                        <%= f.submit "submit" %>

                    <% end %>
                  </div>
                </div>
                <div class="col-md-4">
                  <a href="#">Upload Videos</a>
                  <div style="display: none;">
                    video upload
                  </div>
                </div>
                <div class="col-md-4">
                  <a href="#">Upload Project</a>
                </div>


                </div>


            <% end %>

            <script>
                $('#upload-event').click(function (e) {
                    e.preventDefault()
                    $("#upload-photo").toggle();
                })
            </script>

            <h3>Photos</h3>
            <div class="row">
              <% if @profile.individual_photos.present? %>
                  <% @profile.individual_photos.each do |photo| %>
                      <div class="4u 12u$(mobile)">
                        <article class="item">
                          <%= image_tag photo.portfolio_photo.url, :size => '200x200', :class => 'image fit' %>
                          <header>
                            <h3>My image</h3>
                          </header>
                        </article>
                      </div>
                  <% end %>
              <% else %>
                  <div class="col-md-offset-5">no images available</div>
              <% end %>
            </div>
      <% end %>

    </div>
  </section>

  <!-- About Me -->
  <section id="about" class="three">
    <div class="container">

      <header>
        <h2>About Me</h2>
      </header>

      <a href="#" class="image featured"><img src="images/pic08.jpg" alt="" /></a>

      <p>Hi, I am Nishant Varshney and I mostly attend great gigs </p>

    </div>
  </section>

  <!-- Contact -->
  <section id="contact" class="four">
    <div class="container">

      <header>
        <h2>Contact</h2>
      </header>

      <p>Elementum sem parturient nulla quam placerat viverra
        mauris non cum elit tempus ullamcorper dolor. Libero rutrum ut lacinia
        donec curae mus. Eleifend id porttitor ac ultricies lobortis sem nunc
        orci ridiculus faucibus a consectetur. Porttitor curae mauris urna mi dolor.</p>

      <form method="post" action="#">
        <div class="row">
          <div class="6u 12u$(mobile)"><input type="text" name="name" placeholder="Name" /></div>
          <div class="6u$ 12u$(mobile)"><input type="text" name="email" placeholder="Email" /></div>
          <div class="12u$">
            <textarea name="message" placeholder="Message"></textarea>
          </div>
          <div class="12u$">
            <input type="submit" value="Send Message" />
          </div>
        </div>
      </form>

    </div>
  </section>

</div>

<!-- Footer -->
<!--<div id="footer">-->

<!--&lt;!&ndash; Copyright &ndash;&gt;-->
<!--<ul class="copyright">-->
<!--<li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>-->
<!--</ul>-->

<!--</div>-->
<!--<footer class="navbar navbar-default navbar-fixed-bottom" style="margin-left: 301px;">-->
<!--<p>Created by Joshua Eagle</p>-->
<!--</footer>-->