config/routes.rb
Rails.application.routes.draw do
  devise_for :companies
  root 'welcome#index'
  resources :activities, only: [:index]

  get '/about_us' => 'welcome#about_us'

  devise_scope :company do
  match 'companies/sign_out', to: 'devise/sessions#destroy', via: 'delete'
  end
  devise_scope :individual do
    match 'individuals/sign_out', to: 'devise/sessions#destroy', via: 'delete'
  end

  devise_for :individuals, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations"}
resources :profiles do
  get :autocomplete_tag_name, :on => :collection
end
  resources :individuals do
    resource :profile do
    member do
      post :follow_individual
      post :unfollow_individual
      post :portfolio_photo_uplaod
      post :resume_upload
      post :delete_portfolio
      post :delete_video
      post :update_profile
      end
    end
  end
  get 'tags/:tag' => 'events#index', as: :tag
  get 'classify/:with_classify' => 'events#index', as: :with_classify

  resources :companies do
    resource :company_profile do
      member do
        post :follow_company
        post :unfollow_company
      end
    end
    resources :events do
      member do
        post :follow_event
        post :unfollow_event

      end
      collection do
        get :new_job
      end
      get :job_pending
    end
    resources :company_profiles do
      collection do
        get :job_status
      end
    end

  end

  resources :events do
    collection do
      post 'request_create'
      get 'jobs'
    end
  end
resources :request_events
  resources :videos do
    collection do
      post :create
    end
  end

  resources :categories

resources :projects
  resources :queries do
    collection do
      post :create
    end
  end

resources :seekers

  resources :xviumer_profiles do
    collection do
    get :job_approval
    post :job_approve
      end
  end

  resources :job_feeds

end

app/views/shared/_footer.html.erb
<footer class="page-footer" >


  <div class="container">
    <div class="row">
      <div class="col l4 s12">
        <h5 class="white-text">LetsLogin</h5>
        <p class="grey-text text-lighten-4">Our vision is to find the best opportunity for every talent. Since its inception, the company aims to flourish the part-time culture in the country and set a trend. The part-time industry in India is on boom but highly disorganised and untapped</p>
      </div>
      <div class="col l3 offset-l1 s12">
        <h5 class="white-text"> About </h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="/"> Home </a></li>
          <li><a class="grey-text text-lighten-3" href="/about_us"> About Us </a></li>
          <li><a class="grey-text text-lighten-3" id="works" href="#"> How to Work </a></li>
          <!--<li><a class="grey-text text-lighten-3" href="#!"> Team </a></li>-->
        </ul>
      </div>
      <div class="col l3 offset-l1 s12">
        <h5 class="white-text"> Site Map </h5>
        <ul>
          <li><%= link_to 'Freelance Jobs',  with_classify_path('Freelance'), :target => '_blank', :class => 'grey-text text-lighten-3' %></li>
          <li><%= link_to 'Corporate Jobs',  with_classify_path('Corporate'), :target => '_blank', :class => 'grey-text text-lighten-3' %></li>
          <li><%= link_to 'Startup Jobs',  with_classify_path('Startup'), :target => '_blank', :class => 'grey-text text-lighten-3' %></li>
          <li><%= link_to 'Event Jobs',  with_classify_path('Event'), :target => '_blank', :class => 'grey-text text-lighten-3' %></li>
          <li><%= link_to 'All Jobs',  events_path, :target => '_blank', :class => 'grey-text text-lighten-3' %></li>
        </ul>
      </div>
    </div>
  </div>
  <ul class="icons" style="margin-left: 38%; color: #757575;">
    <li><a href="https://twitter.com/Letsloginhere" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
    <li><a href="https://www.facebook.com/JobzGO" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
    <li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
    <li><a href="in.linkedin.com/in/letslogin" class="icon fa-linkedin"><span class="label">Github</span></a></li>
    <li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
    <li><a href="#" class="icon fa-google-plus"><span class="label">Google+</span></a></li>
  </ul>
  <div class="footer-copyright">
    <div class="container">
      © 2016 Lets Login  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Made with <i class="material-icons" style="padding-top:0px;">favorite</i> by <a style="color:white;" href="http://www.letslogin.in">LetsLogin Team</a>
      <!--<a class="grey-text text-lighten-4 right" href="#!">More Links</a>-->
    </div>
  </div>
</footer>

<!-- Contact button -->


<script>
    $("#works").click(function(e) {
        $('html,body').animate({
                    scrollTop: $("#working-how").offset().top},
                'slow');
        e.preventDefault();

    });
</script>

app/views/shared/_header.html.erb
<header id="header" class=" page-section dark ">

  <div id="header-wrap">

    <div class="container clearfix">

      <div id="primary-menu-trigger"><i class="icon-reorder"></i></div>

      <!-- Logo
      ============================================= -->
      <div id="logo">
        <a href="index.html" class="standard-logo" data-dark-logo="/assets/logo-dark.png"><img src="/assets/logo-dark.png" alt="Let's Login Logo"></a>
        <a href="index.html" class="retina-logo" data-dark-logo="/assets/logo-dark@2x.png"><img src="/assets/logo-dark@2x.png" alt="Let's Login Logo"></a>
      </div><!-- #logo end -->

      <!-- Primary Navigation
      ============================================= -->
      <nav id="primary-menu">

        <ul class="one-page-menu">
          <li class="current"><a href="#" data-href="#header"><div>About</div></a></li>
          <li><a href="#" data-href="#section-features"><div>Events</div></a></li>
          <li><a href="#" data-href="#section-pricing"><div>Membership</div></a></li>
          <% if !individual_signed_in? && !company_signed_in? %>
          <li><a href="#" data-href="#section-testimonials"><div>Login</div></a></li>
          <li><a href="#" data-href="#section-specs"><div>Register</div></a></li>
              <% end %>
          <li><a href="#" data-href="#section-buy"><div>Contact</div></a></li>
         <% if individual_signed_in? %>
              <li><%= link_to "log out", destroy_individual_session_path, method:  :delete %></li>
         <% elsif company_signed_in? %>
              <li><%= link_to "log out", destroy_company_session_path, method:  :delete %></li>
          <% end %>
        </ul>

      </nav><!-- #primary-menu end -->

    </div>

  </div>

</header><!-- #header end -->

app/views/shared/_header_profiles.html.erb
<style>
    nav ul a {
        font-size: 1rem;
        height: 65px;
    }

    .icon_margin {
        margin-top : 5px;
    }

    .header-avatar {
        width: 36px;
        height: 33px;
        margin-bottom: -9px;
    }

    .dropdown-content li {
        margin-left: -10.8%;
        width: 111%;

    }
    .dropdown-content li > a {
        font-size: 1rem;
        color: #fff;
        display: block;
        padding: 1rem 2rem;
    }
</style>

<!-- Navigation Bar-->

<div class="navbar-fixed" style="font-weight: 400;">
  <nav>
    <div class="nav-wrapper">
      <a class="brand-logo" href="/"><img style="width: 153px;" src="/assets/letslogin-logo.png"></a>
      <a href="#!" class="brand-logo center center-cmc hide-on-med-and-down "></a>
      <ul class="right" style="margin-right: 5%;">

        <% if individual_signed_in?  %>
            <li><%= link_to "Home", root_path %></li>
            <li><a id="profile-dropdown-individual" href='#' data-activates='dropdown1'><% if current_individual.profile.avatar_file_name.nil? %><img src="/assets/person.png" class="circle header-avatar" alt="profile-picture" /><% else %><%= image_tag current_individual.profile.avatar.url, :class => 'circle header-avatar' %><% end %><%= current_individual.profile.first_name %><i class="material-icons small" style="float: right;margin-top: 6px;">keyboard_arrow_down</i></a></li>


            <ul id='dropdown1' class='dropdown-content' style="background-color: #ee6e73 !important;">
              <li><%= link_to "Profile", individual_profile_path(current_individual) %></li>
              <li class="divider"></li>
              <li><%= link_to "Edit Profile", edit_individual_profile_path(current_individual) %></li>
              <li class="divider"></li>
              <li><%= link_to "log out", destroy_individual_session_path, method:  :delete %></li>

            </ul>
            </ul>
        <% elsif company_signed_in? %>
            <li><%= link_to "Home", root_path %></li>&nbsp&nbsp
            <li><%= link_to "Profile", company_company_profile_path(current_company) %></li>&nbsp&nbsp
            <li><%= link_to "log out", destroy_company_session_path, method:  :delete %></li>
            <!--<li><a class='dropdown-button' href="#" data-activates='notification_dropdown'><i class="material-icons icon_margin">notifications</i></a></li>-->
            <!--<ul id='notification_dropdown' class='dropdown-content'>-->
              <!--<li><a href="#!"><i class="small material-icons" style="display:inline;">notifications</i> coming soon<span class="badge"></span></a></li>-->
              <!--&lt;!&ndash;<li><a href="#!"><i class="small material-icons" style="display:inline;">notifications</i> notification one<span class="badge">2d ago</span></a></li>&ndash;&gt;-->
              <!--&lt;!&ndash;<li><a href="#!"><i class="small material-icons" style="display:inline;">notifications</i> notification one<span class="badge">2d ago</span></a></li>&ndash;&gt;-->
            <!--</ul>-->
            <li><a href="/"><i class="material-icons icon_margin">exit_to_app</i></a></li>
        <% else %>

            <!-- Dropdown Trigger -->
            <!--<li><a class='dropdown-button' href='#' data-activates='dropdown2'>Sign In </a>-->
              <!--&lt;!&ndash; Dropdown Structure &ndash;&gt;-->
              <!--<ul id='dropdown2' class='dropdown-content'>-->
                <!--<li><%#= link_to "Employee Login", new_individual_session_path %></li>-->
                <!--<li class="divider"></li>-->
                <!--<li><%#= link_to "Company Login", new_company_session_path %></li>-->
              <!--</ul>-->
            <!--</li>-->

            <li><%= link_to "Employee Login", new_individual_session_path %></li>
            <li><%= link_to "Company Login", new_company_session_path %></li>
            <li><a href="/about_us">About Us</a></li>
            <li><a href="/"><i class="material-icons icon_margin">exit_to_app</i></a></li>
        <% end %>
      </ul>
      <a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
    </div>
  </nav>
</div>

<script>
    $('#profile-dropdown-individual').dropdown({
        belowOrigin: true

    });
</script>

app/views/shared/header_backup.html.erb
<style>
    nav ul a {
        font-size: 1rem;
    }
    .icon_margin {
        margin-top : 5px;
    }

    .header-avatar {
        width: 36px;
        height: 33px;
        margin-bottom: -9px;
    }

    .dropdown-content li {
        margin-left: -10.8%;
        width: 111%;

    }
    .dropdown-content li > a {
        font-size: 1rem;
        color: #fff;
        display: block;
        padding: 1rem 2rem;
    }
</style>
<div class="navbar-fixed" style="font-weight: 400;">
  <nav>
    <a class="brand-logo" href="/"><img style="width: 153px;" src="/assets/letslogin-logo.png"></a>
    <ul class="right hide-on-med-and-down" style="margin-right: 5%;">
      <% if individual_signed_in?  %>



          <li><%= link_to "Home", root_path %></li>
          <li><%#= link_to "Job Feeds", job_feeds_path %></li>

          <!--<li><a href="/"><i class="material-icons icon_margin">exit_to_app</i></a></li>-->

          <li><a class="profile-dropdown-individual" href='#' data-activates='dropdown1'><% if current_individual.profile.avatar_file_name.nil? %><img src="/assets/person.png" class="circle header-avatar" alt="profile-picture" /><% else %><%= image_tag current_individual.profile.avatar.url, :class => 'circle header-avatar' %><% end %><%= current_individual.profile.first_name %><i class="material-icons small" style="float: right;margin-top: 6px;">keyboard_arrow_down</i></a></li>


          <ul id='dropdown1' class='dropdown-content' style="background-color: #ee6e73 !important;">
            <li><%= link_to "Profile", individual_profile_path(current_individual) %></li>
            <li class="divider"></li>
            <li><%= link_to "Edit Profile", edit_individual_profile_path(current_individual) %></li>
            <li class="divider"></li>
            <li><%= link_to "log out", destroy_individual_session_path, method:  :delete %></li>

          </ul>

      <% elsif company_signed_in? %>
          <li><%= link_to "Home", root_path %></li>&nbsp&nbsp
          <li><%= link_to "Profile", company_company_profile_path(current_company) %></li>&nbsp&nbsp
          <li><%= link_to "log out", destroy_company_session_path, method:  :delete %></li>
          <!--<li><a class='dropdown-button' href="#" data-activates='notification_dropdown'><i class="material-icons icon_margin">notifications</i></a></li>-->
          <!--<ul id='notification_dropdown' class='dropdown-content'>-->
          <!--<li><a href="#!"><i class="small material-icons" style="display:inline;">notifications</i> coming soon<span class="badge"></span></a></li>-->
          <!--&lt;!&ndash;<li><a href="#!"><i class="small material-icons" style="display:inline;">notifications</i> notification one<span class="badge">2d ago</span></a></li>&ndash;&gt;-->
          <!--&lt;!&ndash;<li><a href="#!"><i class="small material-icons" style="display:inline;">notifications</i> notification one<span class="badge">2d ago</span></a></li>&ndash;&gt;-->
          <!--</ul>-->
          <li><a href="/"><i class="material-icons icon_margin">exit_to_app</i></a></li>
      <% else %>


          <!-- Dropdown Trigger -->
          <!--<li><a class='dropdown-button' href='#' data-activates='dropdown2'>Sign In </a>-->
          <!--&lt;!&ndash; Dropdown Structure &ndash;&gt;-->
          <!--<ul id='dropdown2' class='dropdown-content'>-->
          <!--<li><%#= link_to "Employee Login", new_individual_session_path %></li>-->
          <!--<li class="divider"></li>-->
          <!--<li><%#= link_to "Company Login", new_company_session_path %></li>-->
          <!--</ul>-->
          <!--</li>-->
          <li><%= link_to "Employee Login", new_individual_session_path %></li>
          <li><%= link_to "Company Login", new_company_session_path %></li>
          <li><a href="/about_us">About Us</a></li>
          <li><a href="/"><i class="material-icons icon_margin">exit_to_app</i></a></li>
      <% end %>
    </ul>
    <ul id="slide-out" style="background: #fff !important;"  class="side-nav">
      <% if individual_signed_in?  %>
          <li><%= link_to "Home", root_path %></li>
          <li><a class="profile-dropdown-individual" href='#' data-activates='dropdown1-mobile'><% if current_individual.profile.avatar_file_name.nil? %><img src="/assets/person.png" class="circle header-avatar" alt="profile-picture" /><% else %><%= image_tag current_individual.profile.avatar.url, :class => 'circle header-avatar' %><% end %><%= current_individual.profile.first_name %><i class="material-icons small" style="float: right;margin-top: 6px;">keyboard_arrow_down</i></a></li>
          <ul id='dropdown1-mobile' class='dropdown-content' style="background-color: #ee6e73 !important;">
            <li><%= link_to "Profile", individual_profile_path(current_individual) %></li>
            <li class="divider"></li>
            <li><%= link_to "Edit Profile", edit_individual_profile_path(current_individual) %></li>
            <li class="divider"></li>
            <li><%= link_to "log out", destroy_individual_session_path, method:  :delete %></li>

          </ul>
      <% elsif company_signed_in? %>
          <li><%= link_to "Home", root_path, :class => 'button' %></li>&nbsp&nbsp
          <li><%= link_to "Profile", company_company_profile_path(current_company) %></li>&nbsp&nbsp
          <li><%= link_to "log out", destroy_company_session_path, method:  :delete %></li>
      <% else %>


          <!-- Dropdown Trigger -->
          <!--<li><a class='dropdown-button' href='#' data-activates='dropdown1'>Sign In </a>-->
          <!--&lt;!&ndash; Dropdown Structure &ndash;&gt;-->
          <!--<ul id='dropdown1' class='dropdown-content'>-->
          <!--<li><%#= link_to "Employee Login", new_individual_session_path %></li>-->
          <!--<li class="divider"></li>-->
          <!--<li><%#= link_to "Company Login", new_company_session_path %></li>-->
          <!--</ul>-->
          <!--</li>-->
          <li><%= link_to "Employee Login", new_individual_session_path %></li>
          <li><%= link_to "Company Login", new_company_session_path %></li>
          <li><a href="/about_us">About Us</a></li>
          <li><a href="/"><i class="material-icons icon_margin">exit_to_app</i></a></li>
      <% end %>
    </ul>
    <a style="float: left;" href="#" id="side-nav-profile" data-activates="slide-out-profile" class="button-collapse2 hide-on-large-only"><i  class="material-icons">swap_horiz</i></a>
    <a style="float: right;" href="#" id="side-nav-header" data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
  </nav>
</div>

<script>
    $('#side-nav-header').sideNav({
                menuWidth: 300, // Default is 240
                edge: 'right', // Choose the horizontal origin
                closeOnClick: false // Closes side-nav on <a> clicks, useful for Angular/Meteor
            }
    );

    $('.profile-dropdown-individual').dropdown({
        belowOrigin: true

    });

</script>