config/routes.rb
Rails.application.routes.draw do
  devise_for :companies
  root 'welcome#index'
  resources :activities, only: [:index]

  get '/about_us' => 'welcome#about_us'

  devise_scope :company do
  match 'companies/sign_out', to: 'devise/sessions#destroy', via: 'delete'
  end
  devise_scope :individual do
    match 'individuals/sign_out', to: 'devise/sessions#destroy', via: 'delete'
  end

  devise_for :individuals, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations"}
resources :profiles do
  get :autocomplete_tag_name, :on => :collection
end
  resources :individuals do
    resource :profile do
    member do
      post :follow_individual
      post :unfollow_individual
      post :portfolio_photo_uplaod
      post :resume_upload
      post :delete_portfolio
      post :delete_video
      post :update_profile
      end
    end
  end
  get 'tags/:tag' => 'events#index', as: :tag
  get 'classify/:with_classify' => 'events#index', as: :with_classify

  resources :companies do
    resource :company_profile do
      member do
        post :follow_company
        post :unfollow_company
      end
    end
    resources :events do
      member do
        post :follow_event
        post :unfollow_event

      end
      collection do
        get :new_job
      end
      get :job_pending
    end
    resources :company_profiles do
      collection do
        get :job_status
      end
    end

  end

  resources :events do
    collection do
      post 'request_create'
      get 'jobs'
    end
  end
resources :request_events
  resources :videos do
    collection do
      post :create
    end
  end

  resources :categories

resources :projects
  resources :queries do
    collection do
      post :create
    end
  end

resources :seekers

  resources :xviumer_profiles do
    collection do
    get :job_approval
    post :job_approve
      end
  end

  resources :job_feeds

end

app/models/event.rb
class Event < ActiveRecord::Base

  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller &&  controller.individual_signed_in? ? controller.current_individual : controller.current_company }
  # self.current_individual.id
  serialize :interests
  belongs_to :company
  belongs_to :category
  has_many :videos
  has_many :request_events
  has_many :individuals, through: :request_events
  accepts_nested_attributes_for :request_events
  acts_as_taggable_on :tags
  acts_as_followable

  enum job_status: {pending: 0, approved: 1, rejected: 2, closed: 3}


  has_attached_file :event_avatar, :styles => { :small => "150x150>" },
                    :url  => "/assets/products/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"

  #validates_attachment_presence :event_avatar
  validates_attachment_size :event_avatar, :less_than => 2.megabytes
  validates_attachment_content_type :event_avatar, :content_type => ['image/jpeg', 'image/png']

  filterrific :default_filter_params => { :sorted_by => 'created_at_desc' },
              :available_filters => %w[
                sorted_by
                search_query
                with_category_id
                with_place
                with_type
                with_classify
              ]

  # default for will_paginate
   self.per_page = 9

  scope :with_place, lambda { |place|
                     where( locality: place )

                   }
  scope :with_classify, lambda { |classify|
                     where( job_classify: classify )

                   }
  scope :with_type, lambda { |type|
                           where(type_job: type)
                  }

  scope :with_category_id, lambda { |category_ids|
                          where(category_id: [*category_ids])
                        }

  scope :search_query, lambda { |query|

                       where("name LIKE ?", "%#{query}%")
                     }

  scope :sorted_by, lambda { |sort_option|
                    # extract the sort direction from the param value.
                    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
                    case sort_option.to_s
                      when /^created_at_/
                        # Simple sort on the created_at column.
                        # Make sure to include the table name to avoid ambiguous column names.
                        # Joining on other tables is quite common in Filterrific, and almost
                        # every ActiveRecord table has a 'created_at' column.
                        order("events.created_at #{ direction }")
                      when /^name_/
                        # Simple sort on the name colums
                        order("LOWER(students.last_name) #{ direction }, LOWER(students.first_name) #{ direction }")
                      when /^country_name_/
                        # This sorts by a student's country name, so we need to include
                        # the country. We can't use JOIN since not all students might have
                        # a country.
                        order("LOWER(countries.name) #{ direction }").includes(:country)
                      else
                        raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
                    end
                  }

  def self.options_for_sorted_by
    [
        ['Name (a-z)', 'name_asc'],
        ['Registration date (newest first)', 'created_at_desc'],
        ['Registration date (oldest first)', 'created_at_asc'],
        ['Country (a-z)', 'country_name_asc']
    ]
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  before_action :authenticate_company!, except: [:show, :index, :request_create, :follow_event, :unfollow_event, :jobs]
  before_action :individual_redirect_login, only: [:show]

  def index
    # @events = Event.all
    params[:filterrific][:with_category_id] = params[:with_category_id] unless params[:filterrific].nil?
    params[:filterrific][:with_place] = params[:with_place] unless params[:filterrific].nil?
    params[:filterrific][:with_type] = params[:with_type] unless params[:filterrific].nil?
    params[:filterrific][:with_classify] = params[:with_classify] unless params[:filterrific].nil?

    @filterrific = initialize_filterrific(
        Event,
        params[:filterrific],
        :select_options => {
             sorted_by: Event.options_for_sorted_by,
             with_category_id: Category.options_for_select

        }
    ) or return
    if params[:tag]
      @events = @filterrific.find.paginate(page: params[:page], per_page: 6).where(is_job: true).tagged_with(params[:tag]).where(job_status: 1)
    elsif params[:with_classify]
      @events = @filterrific.find.paginate(page: params[:page], per_page: 6).where(is_job: true).where(job_classify: params[:with_classify]).where(job_status: 1)
    else
      @events = @filterrific.find.paginate(page: params[:page], per_page: 6).where(is_job: true).where(job_status: 1)
    end
p params[:with_classify]
p params
p params[:filterrific]
p '11111111'
    p params[:page]
    p @events
    respond_to do |format|
      format.html
      format.js
    end

  end

  def jobs

    @filterrific_job = initialize_filterrific(
        Event,
        params[:filterrific],
        :select_options => {
            sorted_by: Event.options_for_sorted_by,
            with_category_id: Category.all

        }
    ) or return
    @events_job = @filterrific_job.find.page(params[:page]).where(is_job: true)



    p @events_job

    respond_to do |format|
      format.html
      format.js
    end


  end

  def new
    @event = current_company.events.build
    @categories = Category.all
  end

  def new_job
    @event = current_company.events.build
    @categories = Category.all
  end

  def create
    @event = current_company.events.build(event_params)
    if @event.save
      flash[:success] = "Profile saved"
      redirect_to company_event_job_pending_path(current_company, @event)
    else
      flash[:error] = "Error"
      render :new
    end
  end

  def job_pending

  end

  def update
    @event = Event.where(id: params[:id]).first

      if @event.update_attributes(event_params)
        redirect_to company_event_path(current_company, @event)


    end
  end

  def show
    p params
    p params[:inspect_event].blank?
      @applied_people = RequestEvent.where(:event_id => params[:id]).count
      @event = Event.where(id: params[:id]).first
      @video = Video.where(event_id: params[:id]).all
      if individual_signed_in?
      @request_event = RequestEvent.new
    if RequestEvent.exists?
      @find_req =  RequestEvent.where(individual_id: current_individual.id).first


    end
      @request_presence = RequestEvent.where( "event_id = :event_id and individual_id = :individual_id",
                                              { event_id: params[:id], individual_id: current_individual.id })

   end
      @count_request = RequestEvent.where(event_id: params[:id], status: "inprocess").count
      @request_people = RequestEvent.where(event_id: params[:id], status: "inprocess").pluck(:individual_id)
      @name = Profile.where(individual_id: @request_people)


     @interested_individual = Profile.where(category_id: @event.interests).all
      respond_to do |format|
        format.html
        format.js
      end

  end

  def event_update_info
    @event = Event.where(id: params[:id]).first
    if @event.update_attributes(event_info_params)
      redirect_to company_event_path(current_company, @event)
    end
  end


  def request_create
    p params
    @request_event = RequestEvent.create(request_params)
    if @request_event.save
      @message = 'Your Request has been processed, We will contact you shortly.'
    else
      @message = 'There was a problem creating a request, Please try again.'
    end
    respond_to do |format|
      format.js
    end
  end

  def follow_event
    @event = Event.where(id: params[:id]).first
    if individual_signed_in?
    current_individual.follow(@event)
    elsif company_signed_in? && @event.company_id != current_company.id
      current_company.follow(@event)
    end
    p 'followed'
    respond_to do |format|
      format.js
    end
  end

  def unfollow_event
    @event = Event.where(id: params[:id]).first
    if individual_signed_in?
      current_individual.stop_following(@event)
    elsif company_signed_in? && @event.company_id != current_company.id
      current_company.stop_following(@event)
    end
    p 'followed'
    respond_to do |format|

      format.js { render 'follow_event.js.erb'}
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :company_id, :category_id, :event_date, :event_time, :event_info, :is_job, :place, :event_avatar, :lattitude,
                                  :longitude,:find_name, :venue_name,:sub_locality, :locality,:tag_list, :type_job, :job_classify, :state, :country, :country_code, :postal_code,
                                  :full_address, :education, :gender, :experience, :person_req, :salary, interests: [])
  end

  def request_params
    params.require(:request_event).permit(:individual_id, :event_id, :company_id, :msg, :status)
  end

  def  individual_redirect_login
    unless company_signed_in?
      authenticate_individual!
    end
  end

end

app/helpers/events_helper.rb
module EventsHelper

  def youtube_embed(youtube_url)
    if youtube_url[/youtu\.be\/([^\?]*)/]
      youtube_id = $1
    else
      # Regex from # http://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
      youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
      youtube_id = $5
    end

   return youtube_id
  end

end

app/views/events/_event_info.html.erb
<%= form_for @event, :url => { :action => "update"} do |f| %>
    <%= f.text_area :event_info, :class => 'ckeditor' %>
    <%= f.submit 'submit' %>
    <input type="button" id="close-editor"  value="Cancel"> </input>


<% end %>
<script type="text/javascript" >

    $('#close-editor').click(function() {
        $('#update-info-update').hide();
        $('#update-click').show();
        $('#update-info-show').show();

    });
</script>

app/views/events/_list.html.erb
    <div class="row" id="event-posts">

 <% @events.each do |event| %>
        <div class="col s12 m4">
      <div class="card" style="max-height: 432px;">
        <div class="card-image">
          <% if event.event_avatar_file_name.present? %>
          <%= image_tag event.event_avatar.url, :size => '260x180' %>
              <% else %>
          <img src="/assets/1.jpg"/>
          <% end %>
        </div>
        <div class="card-action-buttons icon-over-image">
      <a class="btn-floating waves-effect waves-light green accent-4"><img src="/assets/Entertainment.png" style="margin-left: 6px;"> </a>
        </div>
        <div class="card-content">
          <h5><%= link_to event.name, company_event_path(event.company.id, event.id) %>
          </h5>
          <span class="location-event">
        <i class="fa fa-map-marker"></i> <%= event.locality %>
      </span></br>
          <span class="timing-event">
            <i class="fa fa-clock-o"></i> Mon, 30 oct 2015
          </span>
        </div>

        <div class="card-action row">
      <span class="col s6">
        stars
      </span>
      <span class="col s6">
        timing
      </span>
        </div>
      </div>
    </div>

 <% end %>
  </div>
    <div class="scroll" id="infinite-scrolling" style="display: none">

      <%= will_paginate  %>

    </div>


<!--row ends-->


<script>

    $('.collapsible').collapsible({
        accordion : false // A setting that changes the collapsible behavior to expandable instead of the default accordion style
    });
</script>

<style>
    .icon-over-image  {

        margin-left: 78%;
        margin-top: -19px;
        height: 16px;
    }
    .scroll {
margin-left: 45%;
    }

</style>

app/views/events/backup.html.erb
<%= form_for_filterrific @filterrific, :class => 'col s12' do |f| %>
    <%= render_filterrific_spinner %>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field(
                    :search_query,
                    class: 'filterrific-periodically-observed validate',
                    id: 'first_name'
            ) %>

        <label for="first_name">Enter keyword</label>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= f.select(
                    :with_category_id,
                    @filterrific.select_options[:with_category_id],
                    { include_blank: '- Any -' },
                    class: 'select-filter'
            ) %>

        <label>select category</label>
      </div>
    </div>
    <%= link_to(
                'Reset filters',
                reset_filterrific_url,
        ) %>
<% end %>

app/views/events/follow_event.js.erb
$('#follow-button').load(document.URL +  ' #follow-button');
$('#followed-count').load(document.URL +  ' #followed-count');

app/views/events/index.html.erb
<%= stylesheet_link_tag 'lets_all_jobs' %>
<%= stylesheet_link_tag 'cmc_css' %>
<%= stylesheet_link_tag 'materialize' %>


<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">






<style>
    #header .button {
        box-shadow: none !important;
    }
    body {
        background: url("/assets/background.jpg");
    }
    .header-avatar {
        width: 36px;
        height: 33px;
        margin-bottom: -9px;
    }
    .dropdown-content {
        overflow: hidden;
    }

    .dropdown-content li {
        margin-left: -10.8%;
        width: 111%;

    }

    .collapsible-header {
        padding: 30px 20rem;

    }
    .dropdown-content li > a {
        font-size: 1rem;
        color: #fff;
        display: block;
        padding: 1rem 2rem;

    }
    .blur {
        -webkit-filter: blur(4px);
        -moz-filter: blur(4px);
        -ms-filter: blur(4px);
        -o-filter: blur(4px);
        filter: blur(4px);
    }

</style>

<style>
    nav ul a {
        font-size: 1rem;
    }
    .icon_margin {
        margin-top : 5px;
    }

    .quick{
        height: 200px;
        width: 15.666667% !important;
        float: right;
        background-color: #FFFFFF;
        z-index: 1;
        position: fixed;

    }
</style>

<%= render partial: 'shared/header_profiles' %>
<div class="container" style="width: 95% !important;">
<div class="row" style="margin-top:30px !important;">

  <div class="col l2 s12 z-depth-1" style="background: rgba(35, 46, 53, 0.89) !important">
  <div class="filter-head" >
    <i class="material-icons small" style="color: #fff; float: left;">search</i><h5 style="color: #fff; font-weight: 500 !important;">Filter Search</h5>
  </div>
    <hr>
    <div>
    <%= form_for_filterrific @filterrific do |f| %>
        <%= f.hidden_field :source , :value => 'event' %>


       <div class="row title">
         <h6 class="center-align" style="color: #fff; font-weight: 500 !important;">Title Search</h6>
         <div class="input-field col s12" style="background: #fff;">
         <%= f.text_field(
                     :search_query,
                     class: 'filterrific-periodically-observed validate',
                     id: 'first_name'
             ) %>
         <label for="first_name">Textarea</label>
       </div>
         </div>


       <div class=" row category">
         <h6 class="center-align" style="color: #fff; font-weight: 500 !important;">Category Search</h6>
         <div class="input-field col s12" style="background: #fff; height: 270px; overflow: scroll;">
         <% Category.all.each_with_index do |a, index| %>

             <%= check_box_tag("with_category_id[]", a.id, false, id: index) %>
             <label style="color: #000 !important;" for=<%= index %>  ><%= a.name %></label></br>
         <% end %>
       </div>
          </div>

          <div class=" row place">
            <h6 class="center-align" style="color: #fff; font-weight: 500 !important;">Location Search</h6>
            <div class="input-field col s12" style="background: #fff; height: 185px; overflow: scroll;">
              <p class="field">
                <%= check_box_tag("with_place[]", "Noida", false, id: "noida") %>
                <label style="color: #000 !important;" for="noida">Noida</label>
              </p>
              <p class="field">
                <%= check_box_tag("with_place[]", "Ghaziabad", false, id: "ghaziabad") %>
                <label style="color: #000 !important;" for="ghaziabad">Mumbai</label>
              </p>
              <p class="field">
                <%= check_box_tag("with_place[]", "Delhi", false, id: "delhi") %>
                <label style="color: #000 !important;" for="delhi">Delhi</label>
              </p>
            </div>
          </div>

          <div class=" row place">
            <h6 class="center-align" style="color: #fff; font-weight: 500 !important;">Type Search</h6>
            <div class="input-field col s12" style="background: #fff; height: 185px; overflow: scroll;">
              <p class="field" >
                <%= check_box_tag("with_type[]", "Fulltime", false, id: "Fulltime") %>
                <label style="color: #000 !important;" for="Fulltime">Fulltime</label>
              </p>
              <p class="field" >
                <%= check_box_tag("with_type[]", "Part-time", false, id: "Part-time") %>
                <label style="color: #000 !important;" for="Part-time">Part Time</label>
              </p>
            </div>
          </div>

        <% end %>
      </div>
  </div>


<div class="col l7 s12"  style=" margin-left: 5%;">
  <div id="filter-focus"></div>
  <div class="row">
    <div class="col l3 card offset-l2 s12 center-align hide-on-med-and-down " style="width: 60%;background: #ee6e73;color: #fff;height: 49px;">
      <h4 style="font-size: 24px;color: #fff;font-weight: 500 !important;margin-top: 10px;" ><%= params[:with_classify].present? ? params[:with_classify] : 'All'  %> Jobs</h4>
    </div>
    <div class="col s12 card  center-align hide-on-large-only " style="margin-left: -5% !important;background: #ee6e73;color: #fff;height: 49px;">
      <h4 style="font-size: 24px;color: #fff;font-weight: 500 !important;margin-top: 10px;" ><%= params[:with_classify].present? ? params[:with_classify] : 'All'  %> Jobs</h4>
    </div>
  </div>

  <div id="filter-spinner" >

    <%#= render_filterrific_spinner %>
        <span class="filterrific_spinner" style="display:none;">
          <div class="preloader-wrapper big active" style="margin-left: 25%;z-index: 99999 !important;margin-top: 14%;position: absolute;">
            <div class="spinner-layer spinner-red-only">
              <div class="circle-clipper left">
                <div class="circle"></div>
              </div><div class="gap-patch">
              <div class="circle"></div>
            </div><div class="circle-clipper right">
              <div class="circle"></div>
            </div>
            </div>
          </div>
        </span>
  </div>

  <div class="row" id="filterrific_results">



    <%= render(
                partial: 'events/job_list',

        ) %>


  </div>

</div>

</div>

  <div class="row hide" style="font-size: 3.5rem !important; background: #fff;">
<div class="col s12">
  <%= form_for_filterrific @filterrific do |f| %>
      <%= f.hidden_field :source , :value => 'event' %>
  <ul class="collapsible col s12" data-collapsible="accordion">
    <li>
      <div class="collapsible-header"><i class="material-icons">filter_drama</i>Title</div>
      <div class="collapsible-body">
        <div class="input-field">
        <%= f.text_field(
            :search_query,
            class: 'filterrific-periodically-observed validate',
            id: 'first_name'
                        ) %>
        <label for="textarea1">Textarea</label>
        </div>
        </div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">place</i>Second</div>
      <div class="collapsible-body">
        <div class="col s12" style="background: #fff; height: 270px; overflow: scroll;">

              <% Category.all.each_with_index do |a, index| %>

                  <%= check_box_tag("with_category_id[]", a.id, false, id: a.name) %>
                  <label style="color: #000 !important;" for=<%= a.name %>  ><%= a.name %></label></br>
              <% end %>

        </div>
      </div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">whatshot</i>Third</div>
      <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
    </li>
  </ul>
      <% end %>


</div>

  </div>




  </div>
<footer class="page-footer center-align">
  <div class="container">
    <div class="row">
      <div class="col l4 s12" >
        <h5 class="white-text">Lets Login</h5>
        <p class="grey-text text-lighten-4">Our vision is to find the best opportunity for every talent. Since its inception, the company aims to flourish the part-time culture in the country and set a trend. The part-time industry in India is on boom but highly disorganised and untapped</p>
      </div>
      <div class="col l3 offset-l1 s12">
        <h5 class="white-text"> About </h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="/"> Home </a></li>
          <li><a class="grey-text text-lighten-3" target="_blank" href="/about_us"> About Us </a></li>
          <li><a class="grey-text text-lighten-3" target="_blank" href="/#working-how"> How it Works ?</a></li>
          <!--<li><a class="grey-text text-lighten-3" href="#!"> Team </a></li>-->
        </ul>
      </div>
      <div class="col l3 offset-l1 s12">
        <h5 class="white-text"> Site Map </h5>
        <ul>
          <li><%= link_to 'Freelance Jobs',  with_classify_path('Freelance'), :target => '_blank', :class => 'grey-text text-lighten-3' %></li>
          <li><%= link_to 'Corporate Jobs',  with_classify_path('Corporate'), :target => '_blank', :class => 'grey-text text-lighten-3' %></li>
          <li><%= link_to 'Startup Jobs',  with_classify_path('Startup'), :target => '_blank', :class => 'grey-text text-lighten-3' %></li>
          <li><%= link_to 'Event Jobs',  with_classify_path('Event'), :target => '_blank', :class => 'grey-text text-lighten-3' %></li>
          <li><%= link_to 'All Jobs',  events_path, :target => '_blank', :class => 'grey-text text-lighten-3' %></li>
        </ul>
      </div>
      <!--<ul class="icons" style="margin-left: 38%; color: #757575;">-->
      <!--<li><a href="https://twitter.com/Letsloginhere" class="icon fa-twitter"><span class="label">Twitter</span></a></li>-->
      <!--<li><a href="https://www.facebook.com/JobzGO" class="icon fa-facebook"><span class="label">Facebook</span></a></li>-->
      <!--<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>-->
      <!--<li><a href="in.linkedin.com/in/letslogin" class="icon fa-linkedin"><span class="label">Github</span></a></li>-->
      <!--<li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>-->
      <!--<li><a href="#" class="icon fa-google-plus"><span class="label">Google+</span></a></li>-->
      <!--</ul>-->
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2016 Lets Login  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Made with <i class="material-icons" style="padding-top:0px;">favorite</i> by <a style="color:white;" href="http://www.letslogin.in">LetsLogin Team</a>
      <!--<a class="grey-text text-lighten-4 right" href="#!">More Links</a>-->

    </div>
  </div>
</footer>

<!-- Scripts -->

<script type="text/javascript">

    $('#profile-dropdown-events').dropdown({
        belowOrigin: true

    });
    $('.collapsible').collapsible({
        accordion : false // A setting that changes the collapsible behavior to expandable instead of the default accordion style
    });
    $(".button-collapse").sideNav();

</script>

app/views/events/job_pending.html.erb
<%= stylesheet_link_tag 'materialize' %>

<%= stylesheet_link_tag 'cmc_css_profile' %>
<%= render :partial => 'shared/header' %>
<div class="row">
  <div class="col l3 card offset-l1 s12 center-align " style="width: 42.5%;margin-left: 28.7%;background: #ee6e73;color: #fff;">
    <h4 style="font-weight: 500 !important;">Job Pending</h4>
  </div>
</div>
<div class="row section scrollspy" id="description">
  <div class="col l9 col s12 offset-l2">

    <section>
      <div class="row">
        <div class="col l11 offset-l1 col s12 z-depth-2 des-cmc" style="margin-left: -4%;">
          <h4 style="font-size: 1.2rem;">Thank you for Posting a job Please wait while our team will verify , you will get a confirmation mail when your job will be active </h4>
          <p>go to your <%= link_to 'profile', company_company_profile_path(current_company) %> or see your <%= link_to 'Jobs Status',job_status_company_company_profiles_path(current_company) %></p>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/events/jobs.html.erb
</br>
</br>
<%= stylesheet_link_tag 'style-event-filter' %>

<%= stylesheet_link_tag 'materialize' %>

<header class="cd-header">
  <h1>Search Jobs</h1>



</header>



<div class="row">
  <div class="col s12">
    <%= link_to 'Events', events_path, :class => 'btn btn-large waves-effect waves-light switch-button' %>
    <%= link_to 'Jobs', jobs_events_path, :class => 'btn btn-large waves-effect waves-light red switch-button' %>
  </div>
  <div id="test1" class="col s12">
    <%= form_for_filterrific @filterrific_job, :class => 'col s12' do |f| %>

        <%= render_filterrific_spinner %>

        <div class="col s12 m3 ">

          <div class="filter-container">
            <strong class="big-font">Filter by</strong>
            <ul class="collapsible" data-collapsible="expandable">
              <li>
                <div class="collapsible-header"><i class="fa fa-search"></i>Name</div>
                <div class="collapsible-body">
                  <div class="input-field col s12">
                    <%= f.text_field(
                                :search_query,
                                class: 'filterrific-periodically-observed validate',
                                id: 'first_name'
                        ) %>

                    <label for="first_name">Enter keyword</label>
                  </div>
                </div>
              </li>
              <li>
                <div class="collapsible-header"><i class="fa fa-anchor"></i>Category</div>
                <div class="collapsible-body">
                  <div class="input-field col s12">
                    <% Category.all.each_with_index do |a, index| %>

                        <%= check_box_tag("with_category_id[]", a.id, false, id: index) %>
                        <label for=<%= index %> ><%= a.name %></label></br>
                    <% end %>

                  </div>
                </div>
              </li>
              <li>
                <div class="collapsible-header"><i class="fa fa-globe"></i>Place</div>
                <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
              </li>
            </ul>

          </div>
          <%= link_to(
                      'Reset filters',
                      reset_filterrific_url,
              ) %>
        </div>
    <% end %>

    <%= render(
                partial: 'events/job_list',

        ) %>
  </div>



</div>



















<script>
    $('.select-filter').material_select();
</script>

app/views/events/request_create.js.erb
$.growl.notice({ message: "<%= @message %>" });